name: CustomItems
version: '${project.version}'
main: me.brzeph.customitems.Main
api-version: '1.20'
depend: [NBTAPI]

commands:
  nbtTags:
    description: gives the nbt tags of the item
    usage: /<command>
  nbt:
    description: changes the nbt tags of an item
    usage: /<command>

  skilltrainer:
    description: opens the skilltrainer GUI
    usage: /<command>

  pick:
    description: gives the player all custom picks
    usage: /<command>
  t1pick:
    description: gives the player a t1 custom pick
    usage: /<command>
  t2pick:
    description: gives the player a t2 custom pick
    usage: /<command>
  t3pick:
    description: gives the player a t3 custom pick
    usage: /<command>
  t4pick:
    description: gives the player a t4 custom pick
    usage: /<command>
  t5pick:
    description: gives the player a t5 custom pick
    usage: /<command>